### ISSUE TITLE
Issues getting it work properly 

### ISSUE THREAD

**Issue by ghost** [gunnarlium/babel-jspm-karma-jasmine-istanbul#10]
Hey. Seems like I got a lot of issues here. Btw. Maybe easier if I write in your own language:

Fulgte tutorialen steg for steg, men kjørte meg fast I en del problemer. Bemerket også at det er en stor forskjell mellom tutorialen og koden på repo. Package.json og kilde filene er forskjellig.

Prøvde å få coverage til å fungere men kunne ikke pga manglende moduler.

Ga opp dette og installerte alt på repo et.  Nå fikk jeg problemer med selve transpile. Likte ikke helt Babel 6.x.

Har dette fungert på Windows?  Mange ganger jeg tester kode fra github.com  som kun fungerer for Mac. 

Hvordan ser ferdig transpiled kode ut? Det var det jeg prøvde å finne ut. Masse bloat ala webpack og browserify eller en ensom fil uten injection av Module loader etc?

Rollup har veldig clean source. Eneste problemet der er injection of babel helpers. 58 linjer med kode jeg ikke trenger.

**Comment by gunnarlium** [comment]
I prefer keeping communication in English, so a wider audience can understand it.

I've tried to keep the tutorial up to date with the changes in the repo, but something might have slipped.

Are you able to get it working by following "quick" version on top of the README? I just ran through the install with both Node 4.2.2 and 5.3.0 (with their respective default npm versions), and everything worked as expected.

I've only tested on Mac OS X, as that's what I have access to. I know several people have it got it running on Linux, but have no reports from Windows users.

## 

As for what the transpiled code looks like, that's really beyond the scope of this repo. Refer to the JSPM docs for that.

There is some extra overhead, and the transpiled code likely looks different than what you would get if you wrote it yourself in ES5. Whether the extra lines of code really matter depends on your project. Unless you're in an extremely resource constrained environment, the benefits of using webpack, jspm, browserify and friends will likely outweigh the cost, at least if you the take time to configure the tools properly for production use.
