### ISSUE TITLE
Exception when using babel@6

### ISSUE THREAD

**Issue by hogart** [gunnarlium/babel-jspm-karma-jasmine-istanbul#14]
Trying to reproduce your setup I'm getting exception on this line: https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/index.js#L168
with stack trace leading to loading my first *.spec.js file. What could be the problem?
I also tried to regress to babel 5, but this gives completely incorrect coverage numbers.

**Comment by gunnarlium** [comment]
You cloned the repo and ran

```
$ npm install -g jspm karma-cli
$ npm install
$ karma start karma.conf.js
```

and got an exception?

Can you provide some more info about your environement? I just ran it on Mac OS X, node v4.4.0, npm 2.14.20, and it still works as expected.

**Comment by hogart** [comment]
Thanks for reply. No, I need to add coverage to existing project, so I copied your karma.conf.js, installed dependencies (same major version) and got an exception. package.json excerpt:

``` json
  "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-polyfill": "^6.7.4",
    "babel-preset-es2015": "^6.6.0",
    "isparta": "^3.5.3",
    "istanbul": "gotwarlost/istanbul.git#source-map",
    "jasmine": "^2.4.1",
    "jasmine-core": "^2.3.4",
    "jspm": "^0.16.33",
    "jspm-git": "^0.4.2",
    "karma": "^0.13.22",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-chrome-launcher": "^0.2.3",
    "karma-coverage": "douglasduteil/karma-coverage#next",
    "karma-jasmine": "^0.3.8",
    "karma-jspm": "^2.1.0",
    "karma-sourcemap-loader": "^0.3.7",
    "systemjs-builder": "^0.15.13",
  }
```

src/config.js

``` js
    "babel": "npm:babel-core@6.7.6",
    "babel-runtime": "npm:babel-runtime@6.6.1",
```

May be the problem is that I use node v5.1, have you ever tried this with 5.x?

**Comment by gunnarlium** [comment]
Works with a fresh install of Node v5.1 and npm 3.3.12 as well.

I don't know how Babel works internally, so don't know what might cause an error at that line. Is there any more details in the error message?

This repo was created while trying to make this work on an exsisting project, with just way too many moving parts and possible error causes. Maybe try to extend this project with a few files and deps from your project, and see where it breaks?

**Comment by hogart** [comment]
Ok, that narrows down potential causes to particular minor versions. The error is too generic unfortunately, I just hoped you encountered something like this and found solution.

Thanks again.

**Comment by hogart** [comment]
I transplanted your config into my code again and now I noticed that despite what README.md says, this setup uses babel@5 (it says so in `src/config.js`). This fixed my problem. Is babel@6 mentioned in package.json actually used?

I also spent some time trying to figure out changes required for more complex project structure, so I'd like to share my findings, but this is topic for entire different PR.

Thanks for amazing boilerplate!

**Comment by gunnarlium** [comment]
Need to dig a bit deeper into this to be sure. I believe the Babel 6 is the used by Karma to process the test files, but the files loaded through JSPM (ie. the source files) are run through Babel 5. I just tried to update JSPM Babel to 6, and that did not work. I don't think JSPM 0.16 is compatible with Babel 6, 0.17 (which is in beta should fix that). However, as JSPM 0.17 changes quite a lot, I think this tutorial needs be rewritten to match the new setup. Probably best to stick with Babel 5 for now.
