### ISSUE TITLE
404 after karma start

### ISSUE THREAD

**Issue by marcinmierzejewski1024** [gunnarlium/babel-jspm-karma-jasmine-istanbul#15]
I completed first part of Your tutorial(frankly I completed it few times just to be sure I did't commit stupid typo), and I still gets 404 error on hello.spec.js

> Mac-Mini:untitled admin$ karma start karma.conf.js
> 04 05 2016 16:19:29.495:WARN [karma]: Port 9876 in use
> 04 05 2016 16:19:29.499:INFO [karma]: Karma v0.13.22 server started at http://localhost:9877/
> 04 05 2016 16:19:29.514:INFO [launcher]: Starting browser PhantomJS
> 04 05 2016 16:19:30.416:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#w8P2jZgpGn7_tVsBAAAA with id 10307519
> PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
>   Error: XHR error (404 Not Found) loading http://localhost:9877/src/hello.spec.js
>         Error loading http://localhost:9877/src/hello.spec.js

If I could use Your help:
https://github.com/marcinmierzejewski1024/babel-jspm-karma-jasmine-istanbul-playground

**Comment by gunnarlium** [comment]
> 04 05 2016 16:19:29.495:WARN [karma]: Port 9876 in use

Are you running multiple instances or using port 9876 for something else?

**Comment by marcinmierzejewski1024** [comment]
And that was the problem. I ignored this, thinking another instance of karma doesn't affect routing. Sorry...
