### ISSUE TITLE
tests fail to run

### ISSUE THREAD

**Issue by outofculture** [gunnarlium/babel-jspm-karma-jasmine-istanbul#3]
```
$ npm install
    ....
$ jspm install
    ....
$ karma start karma.conf.js
WARN [reporter]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?

/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:jspm"! (Resolving: framework:jspm)
    at error (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /usr/local/lib/node_modules/karma/lib/server.js:31:14
    at Array.forEach (native)
    at start (/usr/local/lib/node_modules/karma/lib/server.js:30:21)
    at invoke (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/usr/local/lib/node_modules/karma/lib/server.js:310:12)
    at Object.exports.run (/usr/local/lib/node_modules/karma/lib/cli.js:224:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:3:23)
```

**Comment by gunnarlium** [comment]
I'm seeing the same issue myself, now. Karma fails to install properly, which I suspect might be caused by an update to xcode today. Are you using a Mac?

**Comment by outofculture** [comment]
No, ubuntu. Hunting around, I see some references to the most recent jspm being broken for people...

**Comment by gunnarlium** [comment]
In a similar project I have, tests are working when I run them through gulp, but breaks when using Karma directly.

**Comment by tniswong** [comment]
@outofculture try:

`npm remove -g karma`
`npm install -g karma-cli`

The tests still don't actually get run for me, but thats another issue.

**Comment by gunnarlium** [comment]
I've slightly updated to quick start, to include installation of jspm and karma-cli globally, and everything works as expected for at least Node.js v0.12.7 and 4.1.1.

@tniswong Do you receive any error messages?

**Comment by tniswong** [comment]
@gunnarlium when I run `karma start` this is what I get:

```
$ karma start
WARN [karma]: Port 9876 in use
INFO [karma]: Karma v0.12.37 server started at http://localhost:9877/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket rDGMM4WPYT3xNpExv4Cz with id 66591171
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
Post-processing using source maps

=============================== Coverage summary ===============================
Statements   : 100% ( 2/2 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 2/2 )
================================================================================
```

Notice specifically this line: `PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.002 secs / 0 secs)` It's not actually executing any tests.

**Comment by gunnarlium** [comment]
Looks like port 9876 is in use already. Do you have another tab/process running?

**Comment by tniswong** [comment]
Also, I found this repo after I followed your blog post. I modified the instructions in your post slightly and was able to get everything working.

In addition to everything you had, I added `karma-jasmine-html-reporter` so I could run the code via jasmine in the browser and I noticed that I get no sourcemaps for the instrumented source code. The actual sourcemaps for the tests/specs work great though.

**Comment by tniswong** [comment]
Haha, yeah probably. damnit. Checking it out. Don't know how I missed that line.

**Comment by tniswong** [comment]
Yeah, that worked.

**Comment by gunnarlium** [comment]
Great! Any modified instructions you should be included in this repo or the blog post? I've added two small commits just now.

**Comment by outofculture** [comment]
Works for me now. Thanks!

**Comment by tniswong** [comment]
Not really, it was pretty straight forward. However, the addition of the `karma-jasmine-html-reporter` may be helpful for some.

I also just figured out that if I remove coverage preprocessor, I get the sourcemaps properly on the debug page. Need to figure out how to get the two to play nice.

**Comment by tniswong** [comment]
Do you have any plans to add Angular into this mix?

**Comment by gunnarlium** [comment]
In the "real" project this was extracted from, I'm using Angular. But don't think there's anything special needed to make it work with Angular.
