### ISSUE TITLE
Can't import file into test

### ISSUE THREAD

**Issue by ackerdev** [gunnarlium/babel-jspm-karma-jasmine-istanbul#4]
I'm trying to replicate this setup in a project that uses Angular & Mocha, but I'm having an issue where karma (or perhaps more specifically karma-jspm) will load test files, but can't seem to load the application files when imported into the tests.

Here's all I have in `src/app.spec.js`:

``` js
import * from "app"
```

When karma gets here, it attempts to load `app` from `/base/app.js`, even though the file should actually live under `/base/src/app.js`. Any ideas why this might be happening and how to fix it?

Perhaps related, I had to remove your karma.conf `proxies` config, as it resulted in karma recursively adding `/src` to the path (eg. `/base/src/src/src/src/.../somefile.js`). Was I just doing something wrong here?

**Comment by gunnarlium** [comment]
The recursive thing happens when you try to include a file that doesn't exist. What the proxy does is to tell Karma to look for the file `/base/app.js` in the folder `/base/src.js/`. I assume you also have a file `src/app.js`? You would get recursion if that file is missing.

Also, try doing `import * from "./app"`. Shouldn't be needed if you've set up the jspm config correctly, but that removes one possible problem.

**Comment by ackerdev** [comment]
Yes, `src/app.js` exists. Changing the import to `./app` does not change the recursive path issue with the proxies. I believe it does solve it being actually unable to find app.js when the proxies are removed though, as my errors now reside in the karma test 404ing on jspm_package assets (which app.js imports, leading me to believe it is properly being imported now and its imports are now the ones failing), though it seems this may be a problem with my jspm setup as it simply seems to be looking for the wrong versions for angular packages.

https://github.com/ackerdev/jspm-ionic-starter is the base that I am trying to integrate karma/mocha testing into, if you're interested to get a better look at how my setup is organized. My jspm setup differs from common setups in that it is meant for a cordova app, so config.js and jspm_packages live outside of the web root (www, which is generated via npm build scripts). I don't foresee this affecting karma since it's none the wiser of where my web root resides but maybe I've got something misconfigured or just configured differently in such a way that is messing with this karma setup.

**Comment by ackerdev** [comment]
It seems that somehow jspm installed version `1.4.7` for angular, but mapped declarations for `1.4.6` versions, which were not installed. Removing jspm_packages and re-installing thru jspm did set up matching versions (though for some reason it chose `1.4.6` instead of the newer `1.4.7` which should match my version constraints, but that's something for me to look into).

For my setup, it seems that the `proxies` configuration object is unnecessary, as my tests now work with and without, but leaving it in causes massive error output if I run into improper requires. Am I perhaps doing something differently without realizing it, or is it perhaps truly unnecessary?

Anyway, I think this issue is resolved and can be closed.
